displayName: "Hiring Agent API 5xx Spike"
combiner: "OR"
conditions:
  - displayName: "5xx ratio > 5%"
    conditionThreshold:
      filter: metric.type="run.googleapis.com/request_count" AND resource.type="cloud_run_revision"
      aggregations:
        - alignmentPeriod: 300s
          perSeriesAligner: ALIGN_RATE
          crossSeriesReducer: REDUCE_SUM
          groupByFields:
            - metric.label.response_code_class
      comparison: COMPARISON_GT
      thresholdValue: 0.05
      duration: 300s
      trigger:
        count: 1
notificationChannels: []
documentation:
  content: "High 5xx rate detected on Hiring Agent API. Check /metrics and Cloud Run logs."
  mimeType: "text/markdown"

